
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Profile
 * 
 */
export type Profile = Prisma.ProfileModel
/**
 * Model ProfileTranslation
 * 
 */
export type ProfileTranslation = Prisma.ProfileTranslationModel
/**
 * Model Experience
 * 
 */
export type Experience = Prisma.ExperienceModel
/**
 * Model ExperienceTranslation
 * 
 */
export type ExperienceTranslation = Prisma.ExperienceTranslationModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model ProjectTranslation
 * 
 */
export type ProjectTranslation = Prisma.ProjectTranslationModel
/**
 * Model Post
 * 
 */
export type Post = Prisma.PostModel
/**
 * Model PostTranslation
 * 
 */
export type PostTranslation = Prisma.PostTranslationModel
