
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProfileTranslation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProfileTranslation
 * 
 */
export type ProfileTranslationModel = runtime.Types.Result.DefaultSelection<Prisma.$ProfileTranslationPayload>

export type AggregateProfileTranslation = {
  _count: ProfileTranslationCountAggregateOutputType | null
  _min: ProfileTranslationMinAggregateOutputType | null
  _max: ProfileTranslationMaxAggregateOutputType | null
}

export type ProfileTranslationMinAggregateOutputType = {
  id: string | null
  profileId: string | null
  language: string | null
  bio: string | null
  cvUrl: string | null
}

export type ProfileTranslationMaxAggregateOutputType = {
  id: string | null
  profileId: string | null
  language: string | null
  bio: string | null
  cvUrl: string | null
}

export type ProfileTranslationCountAggregateOutputType = {
  id: number
  profileId: number
  language: number
  bio: number
  cvUrl: number
  _all: number
}


export type ProfileTranslationMinAggregateInputType = {
  id?: true
  profileId?: true
  language?: true
  bio?: true
  cvUrl?: true
}

export type ProfileTranslationMaxAggregateInputType = {
  id?: true
  profileId?: true
  language?: true
  bio?: true
  cvUrl?: true
}

export type ProfileTranslationCountAggregateInputType = {
  id?: true
  profileId?: true
  language?: true
  bio?: true
  cvUrl?: true
  _all?: true
}

export type ProfileTranslationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProfileTranslation to aggregate.
   */
  where?: Prisma.ProfileTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileTranslations to fetch.
   */
  orderBy?: Prisma.ProfileTranslationOrderByWithRelationInput | Prisma.ProfileTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProfileTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProfileTranslations
  **/
  _count?: true | ProfileTranslationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProfileTranslationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProfileTranslationMaxAggregateInputType
}

export type GetProfileTranslationAggregateType<T extends ProfileTranslationAggregateArgs> = {
      [P in keyof T & keyof AggregateProfileTranslation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProfileTranslation[P]>
    : Prisma.GetScalarType<T[P], AggregateProfileTranslation[P]>
}




export type ProfileTranslationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProfileTranslationWhereInput
  orderBy?: Prisma.ProfileTranslationOrderByWithAggregationInput | Prisma.ProfileTranslationOrderByWithAggregationInput[]
  by: Prisma.ProfileTranslationScalarFieldEnum[] | Prisma.ProfileTranslationScalarFieldEnum
  having?: Prisma.ProfileTranslationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProfileTranslationCountAggregateInputType | true
  _min?: ProfileTranslationMinAggregateInputType
  _max?: ProfileTranslationMaxAggregateInputType
}

export type ProfileTranslationGroupByOutputType = {
  id: string
  profileId: string
  language: string
  bio: string | null
  cvUrl: string | null
  _count: ProfileTranslationCountAggregateOutputType | null
  _min: ProfileTranslationMinAggregateOutputType | null
  _max: ProfileTranslationMaxAggregateOutputType | null
}

type GetProfileTranslationGroupByPayload<T extends ProfileTranslationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProfileTranslationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProfileTranslationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProfileTranslationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProfileTranslationGroupByOutputType[P]>
      }
    >
  >



export type ProfileTranslationWhereInput = {
  AND?: Prisma.ProfileTranslationWhereInput | Prisma.ProfileTranslationWhereInput[]
  OR?: Prisma.ProfileTranslationWhereInput[]
  NOT?: Prisma.ProfileTranslationWhereInput | Prisma.ProfileTranslationWhereInput[]
  id?: Prisma.StringFilter<"ProfileTranslation"> | string
  profileId?: Prisma.StringFilter<"ProfileTranslation"> | string
  language?: Prisma.StringFilter<"ProfileTranslation"> | string
  bio?: Prisma.StringNullableFilter<"ProfileTranslation"> | string | null
  cvUrl?: Prisma.StringNullableFilter<"ProfileTranslation"> | string | null
  profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
}

export type ProfileTranslationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  language?: Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  cvUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  profile?: Prisma.ProfileOrderByWithRelationInput
}

export type ProfileTranslationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  profileId_language?: Prisma.ProfileTranslationProfileIdLanguageCompoundUniqueInput
  AND?: Prisma.ProfileTranslationWhereInput | Prisma.ProfileTranslationWhereInput[]
  OR?: Prisma.ProfileTranslationWhereInput[]
  NOT?: Prisma.ProfileTranslationWhereInput | Prisma.ProfileTranslationWhereInput[]
  profileId?: Prisma.StringFilter<"ProfileTranslation"> | string
  language?: Prisma.StringFilter<"ProfileTranslation"> | string
  bio?: Prisma.StringNullableFilter<"ProfileTranslation"> | string | null
  cvUrl?: Prisma.StringNullableFilter<"ProfileTranslation"> | string | null
  profile?: Prisma.XOR<Prisma.ProfileScalarRelationFilter, Prisma.ProfileWhereInput>
}, "id" | "profileId_language">

export type ProfileTranslationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  language?: Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  cvUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProfileTranslationCountOrderByAggregateInput
  _max?: Prisma.ProfileTranslationMaxOrderByAggregateInput
  _min?: Prisma.ProfileTranslationMinOrderByAggregateInput
}

export type ProfileTranslationScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProfileTranslationScalarWhereWithAggregatesInput | Prisma.ProfileTranslationScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProfileTranslationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProfileTranslationScalarWhereWithAggregatesInput | Prisma.ProfileTranslationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProfileTranslation"> | string
  profileId?: Prisma.StringWithAggregatesFilter<"ProfileTranslation"> | string
  language?: Prisma.StringWithAggregatesFilter<"ProfileTranslation"> | string
  bio?: Prisma.StringNullableWithAggregatesFilter<"ProfileTranslation"> | string | null
  cvUrl?: Prisma.StringNullableWithAggregatesFilter<"ProfileTranslation"> | string | null
}

export type ProfileTranslationCreateInput = {
  id?: string
  language: string
  bio?: string | null
  cvUrl?: string | null
  profile: Prisma.ProfileCreateNestedOneWithoutTranslationsInput
}

export type ProfileTranslationUncheckedCreateInput = {
  id?: string
  profileId: string
  language: string
  bio?: string | null
  cvUrl?: string | null
}

export type ProfileTranslationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cvUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profile?: Prisma.ProfileUpdateOneRequiredWithoutTranslationsNestedInput
}

export type ProfileTranslationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cvUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProfileTranslationCreateManyInput = {
  id?: string
  profileId: string
  language: string
  bio?: string | null
  cvUrl?: string | null
}

export type ProfileTranslationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cvUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProfileTranslationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profileId?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cvUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProfileTranslationListRelationFilter = {
  every?: Prisma.ProfileTranslationWhereInput
  some?: Prisma.ProfileTranslationWhereInput
  none?: Prisma.ProfileTranslationWhereInput
}

export type ProfileTranslationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProfileTranslationProfileIdLanguageCompoundUniqueInput = {
  profileId: string
  language: string
}

export type ProfileTranslationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  language?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  cvUrl?: Prisma.SortOrder
}

export type ProfileTranslationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  language?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  cvUrl?: Prisma.SortOrder
}

export type ProfileTranslationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profileId?: Prisma.SortOrder
  language?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  cvUrl?: Prisma.SortOrder
}

export type ProfileTranslationCreateNestedManyWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.ProfileTranslationCreateWithoutProfileInput, Prisma.ProfileTranslationUncheckedCreateWithoutProfileInput> | Prisma.ProfileTranslationCreateWithoutProfileInput[] | Prisma.ProfileTranslationUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.ProfileTranslationCreateOrConnectWithoutProfileInput | Prisma.ProfileTranslationCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.ProfileTranslationCreateManyProfileInputEnvelope
  connect?: Prisma.ProfileTranslationWhereUniqueInput | Prisma.ProfileTranslationWhereUniqueInput[]
}

export type ProfileTranslationUncheckedCreateNestedManyWithoutProfileInput = {
  create?: Prisma.XOR<Prisma.ProfileTranslationCreateWithoutProfileInput, Prisma.ProfileTranslationUncheckedCreateWithoutProfileInput> | Prisma.ProfileTranslationCreateWithoutProfileInput[] | Prisma.ProfileTranslationUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.ProfileTranslationCreateOrConnectWithoutProfileInput | Prisma.ProfileTranslationCreateOrConnectWithoutProfileInput[]
  createMany?: Prisma.ProfileTranslationCreateManyProfileInputEnvelope
  connect?: Prisma.ProfileTranslationWhereUniqueInput | Prisma.ProfileTranslationWhereUniqueInput[]
}

export type ProfileTranslationUpdateManyWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileTranslationCreateWithoutProfileInput, Prisma.ProfileTranslationUncheckedCreateWithoutProfileInput> | Prisma.ProfileTranslationCreateWithoutProfileInput[] | Prisma.ProfileTranslationUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.ProfileTranslationCreateOrConnectWithoutProfileInput | Prisma.ProfileTranslationCreateOrConnectWithoutProfileInput[]
  upsert?: Prisma.ProfileTranslationUpsertWithWhereUniqueWithoutProfileInput | Prisma.ProfileTranslationUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.ProfileTranslationCreateManyProfileInputEnvelope
  set?: Prisma.ProfileTranslationWhereUniqueInput | Prisma.ProfileTranslationWhereUniqueInput[]
  disconnect?: Prisma.ProfileTranslationWhereUniqueInput | Prisma.ProfileTranslationWhereUniqueInput[]
  delete?: Prisma.ProfileTranslationWhereUniqueInput | Prisma.ProfileTranslationWhereUniqueInput[]
  connect?: Prisma.ProfileTranslationWhereUniqueInput | Prisma.ProfileTranslationWhereUniqueInput[]
  update?: Prisma.ProfileTranslationUpdateWithWhereUniqueWithoutProfileInput | Prisma.ProfileTranslationUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?: Prisma.ProfileTranslationUpdateManyWithWhereWithoutProfileInput | Prisma.ProfileTranslationUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.ProfileTranslationScalarWhereInput | Prisma.ProfileTranslationScalarWhereInput[]
}

export type ProfileTranslationUncheckedUpdateManyWithoutProfileNestedInput = {
  create?: Prisma.XOR<Prisma.ProfileTranslationCreateWithoutProfileInput, Prisma.ProfileTranslationUncheckedCreateWithoutProfileInput> | Prisma.ProfileTranslationCreateWithoutProfileInput[] | Prisma.ProfileTranslationUncheckedCreateWithoutProfileInput[]
  connectOrCreate?: Prisma.ProfileTranslationCreateOrConnectWithoutProfileInput | Prisma.ProfileTranslationCreateOrConnectWithoutProfileInput[]
  upsert?: Prisma.ProfileTranslationUpsertWithWhereUniqueWithoutProfileInput | Prisma.ProfileTranslationUpsertWithWhereUniqueWithoutProfileInput[]
  createMany?: Prisma.ProfileTranslationCreateManyProfileInputEnvelope
  set?: Prisma.ProfileTranslationWhereUniqueInput | Prisma.ProfileTranslationWhereUniqueInput[]
  disconnect?: Prisma.ProfileTranslationWhereUniqueInput | Prisma.ProfileTranslationWhereUniqueInput[]
  delete?: Prisma.ProfileTranslationWhereUniqueInput | Prisma.ProfileTranslationWhereUniqueInput[]
  connect?: Prisma.ProfileTranslationWhereUniqueInput | Prisma.ProfileTranslationWhereUniqueInput[]
  update?: Prisma.ProfileTranslationUpdateWithWhereUniqueWithoutProfileInput | Prisma.ProfileTranslationUpdateWithWhereUniqueWithoutProfileInput[]
  updateMany?: Prisma.ProfileTranslationUpdateManyWithWhereWithoutProfileInput | Prisma.ProfileTranslationUpdateManyWithWhereWithoutProfileInput[]
  deleteMany?: Prisma.ProfileTranslationScalarWhereInput | Prisma.ProfileTranslationScalarWhereInput[]
}

export type ProfileTranslationCreateWithoutProfileInput = {
  id?: string
  language: string
  bio?: string | null
  cvUrl?: string | null
}

export type ProfileTranslationUncheckedCreateWithoutProfileInput = {
  id?: string
  language: string
  bio?: string | null
  cvUrl?: string | null
}

export type ProfileTranslationCreateOrConnectWithoutProfileInput = {
  where: Prisma.ProfileTranslationWhereUniqueInput
  create: Prisma.XOR<Prisma.ProfileTranslationCreateWithoutProfileInput, Prisma.ProfileTranslationUncheckedCreateWithoutProfileInput>
}

export type ProfileTranslationCreateManyProfileInputEnvelope = {
  data: Prisma.ProfileTranslationCreateManyProfileInput | Prisma.ProfileTranslationCreateManyProfileInput[]
  skipDuplicates?: boolean
}

export type ProfileTranslationUpsertWithWhereUniqueWithoutProfileInput = {
  where: Prisma.ProfileTranslationWhereUniqueInput
  update: Prisma.XOR<Prisma.ProfileTranslationUpdateWithoutProfileInput, Prisma.ProfileTranslationUncheckedUpdateWithoutProfileInput>
  create: Prisma.XOR<Prisma.ProfileTranslationCreateWithoutProfileInput, Prisma.ProfileTranslationUncheckedCreateWithoutProfileInput>
}

export type ProfileTranslationUpdateWithWhereUniqueWithoutProfileInput = {
  where: Prisma.ProfileTranslationWhereUniqueInput
  data: Prisma.XOR<Prisma.ProfileTranslationUpdateWithoutProfileInput, Prisma.ProfileTranslationUncheckedUpdateWithoutProfileInput>
}

export type ProfileTranslationUpdateManyWithWhereWithoutProfileInput = {
  where: Prisma.ProfileTranslationScalarWhereInput
  data: Prisma.XOR<Prisma.ProfileTranslationUpdateManyMutationInput, Prisma.ProfileTranslationUncheckedUpdateManyWithoutProfileInput>
}

export type ProfileTranslationScalarWhereInput = {
  AND?: Prisma.ProfileTranslationScalarWhereInput | Prisma.ProfileTranslationScalarWhereInput[]
  OR?: Prisma.ProfileTranslationScalarWhereInput[]
  NOT?: Prisma.ProfileTranslationScalarWhereInput | Prisma.ProfileTranslationScalarWhereInput[]
  id?: Prisma.StringFilter<"ProfileTranslation"> | string
  profileId?: Prisma.StringFilter<"ProfileTranslation"> | string
  language?: Prisma.StringFilter<"ProfileTranslation"> | string
  bio?: Prisma.StringNullableFilter<"ProfileTranslation"> | string | null
  cvUrl?: Prisma.StringNullableFilter<"ProfileTranslation"> | string | null
}

export type ProfileTranslationCreateManyProfileInput = {
  id?: string
  language: string
  bio?: string | null
  cvUrl?: string | null
}

export type ProfileTranslationUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cvUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProfileTranslationUncheckedUpdateWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cvUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProfileTranslationUncheckedUpdateManyWithoutProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  language?: Prisma.StringFieldUpdateOperationsInput | string
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cvUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type ProfileTranslationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profileId?: boolean
  language?: boolean
  bio?: boolean
  cvUrl?: boolean
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profileTranslation"]>

export type ProfileTranslationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profileId?: boolean
  language?: boolean
  bio?: boolean
  cvUrl?: boolean
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profileTranslation"]>

export type ProfileTranslationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profileId?: boolean
  language?: boolean
  bio?: boolean
  cvUrl?: boolean
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["profileTranslation"]>

export type ProfileTranslationSelectScalar = {
  id?: boolean
  profileId?: boolean
  language?: boolean
  bio?: boolean
  cvUrl?: boolean
}

export type ProfileTranslationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "profileId" | "language" | "bio" | "cvUrl", ExtArgs["result"]["profileTranslation"]>
export type ProfileTranslationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}
export type ProfileTranslationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}
export type ProfileTranslationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profile?: boolean | Prisma.ProfileDefaultArgs<ExtArgs>
}

export type $ProfileTranslationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProfileTranslation"
  objects: {
    profile: Prisma.$ProfilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    profileId: string
    language: string
    bio: string | null
    cvUrl: string | null
  }, ExtArgs["result"]["profileTranslation"]>
  composites: {}
}

export type ProfileTranslationGetPayload<S extends boolean | null | undefined | ProfileTranslationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload, S>

export type ProfileTranslationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProfileTranslationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProfileTranslationCountAggregateInputType | true
  }

export interface ProfileTranslationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProfileTranslation'], meta: { name: 'ProfileTranslation' } }
  /**
   * Find zero or one ProfileTranslation that matches the filter.
   * @param {ProfileTranslationFindUniqueArgs} args - Arguments to find a ProfileTranslation
   * @example
   * // Get one ProfileTranslation
   * const profileTranslation = await prisma.profileTranslation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProfileTranslationFindUniqueArgs>(args: Prisma.SelectSubset<T, ProfileTranslationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProfileTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProfileTranslation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProfileTranslationFindUniqueOrThrowArgs} args - Arguments to find a ProfileTranslation
   * @example
   * // Get one ProfileTranslation
   * const profileTranslation = await prisma.profileTranslation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProfileTranslationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProfileTranslationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProfileTranslation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileTranslationFindFirstArgs} args - Arguments to find a ProfileTranslation
   * @example
   * // Get one ProfileTranslation
   * const profileTranslation = await prisma.profileTranslation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProfileTranslationFindFirstArgs>(args?: Prisma.SelectSubset<T, ProfileTranslationFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProfileTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProfileTranslation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileTranslationFindFirstOrThrowArgs} args - Arguments to find a ProfileTranslation
   * @example
   * // Get one ProfileTranslation
   * const profileTranslation = await prisma.profileTranslation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProfileTranslationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProfileTranslationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProfileTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProfileTranslations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileTranslationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProfileTranslations
   * const profileTranslations = await prisma.profileTranslation.findMany()
   * 
   * // Get first 10 ProfileTranslations
   * const profileTranslations = await prisma.profileTranslation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const profileTranslationWithIdOnly = await prisma.profileTranslation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProfileTranslationFindManyArgs>(args?: Prisma.SelectSubset<T, ProfileTranslationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProfileTranslation.
   * @param {ProfileTranslationCreateArgs} args - Arguments to create a ProfileTranslation.
   * @example
   * // Create one ProfileTranslation
   * const ProfileTranslation = await prisma.profileTranslation.create({
   *   data: {
   *     // ... data to create a ProfileTranslation
   *   }
   * })
   * 
   */
  create<T extends ProfileTranslationCreateArgs>(args: Prisma.SelectSubset<T, ProfileTranslationCreateArgs<ExtArgs>>): Prisma.Prisma__ProfileTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProfileTranslations.
   * @param {ProfileTranslationCreateManyArgs} args - Arguments to create many ProfileTranslations.
   * @example
   * // Create many ProfileTranslations
   * const profileTranslation = await prisma.profileTranslation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProfileTranslationCreateManyArgs>(args?: Prisma.SelectSubset<T, ProfileTranslationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProfileTranslations and returns the data saved in the database.
   * @param {ProfileTranslationCreateManyAndReturnArgs} args - Arguments to create many ProfileTranslations.
   * @example
   * // Create many ProfileTranslations
   * const profileTranslation = await prisma.profileTranslation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProfileTranslations and only return the `id`
   * const profileTranslationWithIdOnly = await prisma.profileTranslation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProfileTranslationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProfileTranslationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProfileTranslation.
   * @param {ProfileTranslationDeleteArgs} args - Arguments to delete one ProfileTranslation.
   * @example
   * // Delete one ProfileTranslation
   * const ProfileTranslation = await prisma.profileTranslation.delete({
   *   where: {
   *     // ... filter to delete one ProfileTranslation
   *   }
   * })
   * 
   */
  delete<T extends ProfileTranslationDeleteArgs>(args: Prisma.SelectSubset<T, ProfileTranslationDeleteArgs<ExtArgs>>): Prisma.Prisma__ProfileTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProfileTranslation.
   * @param {ProfileTranslationUpdateArgs} args - Arguments to update one ProfileTranslation.
   * @example
   * // Update one ProfileTranslation
   * const profileTranslation = await prisma.profileTranslation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProfileTranslationUpdateArgs>(args: Prisma.SelectSubset<T, ProfileTranslationUpdateArgs<ExtArgs>>): Prisma.Prisma__ProfileTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProfileTranslations.
   * @param {ProfileTranslationDeleteManyArgs} args - Arguments to filter ProfileTranslations to delete.
   * @example
   * // Delete a few ProfileTranslations
   * const { count } = await prisma.profileTranslation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProfileTranslationDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProfileTranslationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProfileTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileTranslationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProfileTranslations
   * const profileTranslation = await prisma.profileTranslation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProfileTranslationUpdateManyArgs>(args: Prisma.SelectSubset<T, ProfileTranslationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProfileTranslations and returns the data updated in the database.
   * @param {ProfileTranslationUpdateManyAndReturnArgs} args - Arguments to update many ProfileTranslations.
   * @example
   * // Update many ProfileTranslations
   * const profileTranslation = await prisma.profileTranslation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProfileTranslations and only return the `id`
   * const profileTranslationWithIdOnly = await prisma.profileTranslation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProfileTranslationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProfileTranslationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProfileTranslation.
   * @param {ProfileTranslationUpsertArgs} args - Arguments to update or create a ProfileTranslation.
   * @example
   * // Update or create a ProfileTranslation
   * const profileTranslation = await prisma.profileTranslation.upsert({
   *   create: {
   *     // ... data to create a ProfileTranslation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProfileTranslation we want to update
   *   }
   * })
   */
  upsert<T extends ProfileTranslationUpsertArgs>(args: Prisma.SelectSubset<T, ProfileTranslationUpsertArgs<ExtArgs>>): Prisma.Prisma__ProfileTranslationClient<runtime.Types.Result.GetResult<Prisma.$ProfileTranslationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProfileTranslations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileTranslationCountArgs} args - Arguments to filter ProfileTranslations to count.
   * @example
   * // Count the number of ProfileTranslations
   * const count = await prisma.profileTranslation.count({
   *   where: {
   *     // ... the filter for the ProfileTranslations we want to count
   *   }
   * })
  **/
  count<T extends ProfileTranslationCountArgs>(
    args?: Prisma.Subset<T, ProfileTranslationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProfileTranslationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProfileTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileTranslationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProfileTranslationAggregateArgs>(args: Prisma.Subset<T, ProfileTranslationAggregateArgs>): Prisma.PrismaPromise<GetProfileTranslationAggregateType<T>>

  /**
   * Group by ProfileTranslation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProfileTranslationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProfileTranslationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProfileTranslationGroupByArgs['orderBy'] }
      : { orderBy?: ProfileTranslationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProfileTranslationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProfileTranslationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProfileTranslation model
 */
readonly fields: ProfileTranslationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProfileTranslation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProfileTranslationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profile<T extends Prisma.ProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__ProfileClient<runtime.Types.Result.GetResult<Prisma.$ProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProfileTranslation model
 */
export interface ProfileTranslationFieldRefs {
  readonly id: Prisma.FieldRef<"ProfileTranslation", 'String'>
  readonly profileId: Prisma.FieldRef<"ProfileTranslation", 'String'>
  readonly language: Prisma.FieldRef<"ProfileTranslation", 'String'>
  readonly bio: Prisma.FieldRef<"ProfileTranslation", 'String'>
  readonly cvUrl: Prisma.FieldRef<"ProfileTranslation", 'String'>
}
    

// Custom InputTypes
/**
 * ProfileTranslation findUnique
 */
export type ProfileTranslationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProfileTranslation to fetch.
   */
  where: Prisma.ProfileTranslationWhereUniqueInput
}

/**
 * ProfileTranslation findUniqueOrThrow
 */
export type ProfileTranslationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProfileTranslation to fetch.
   */
  where: Prisma.ProfileTranslationWhereUniqueInput
}

/**
 * ProfileTranslation findFirst
 */
export type ProfileTranslationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProfileTranslation to fetch.
   */
  where?: Prisma.ProfileTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileTranslations to fetch.
   */
  orderBy?: Prisma.ProfileTranslationOrderByWithRelationInput | Prisma.ProfileTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProfileTranslations.
   */
  cursor?: Prisma.ProfileTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProfileTranslations.
   */
  distinct?: Prisma.ProfileTranslationScalarFieldEnum | Prisma.ProfileTranslationScalarFieldEnum[]
}

/**
 * ProfileTranslation findFirstOrThrow
 */
export type ProfileTranslationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProfileTranslation to fetch.
   */
  where?: Prisma.ProfileTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileTranslations to fetch.
   */
  orderBy?: Prisma.ProfileTranslationOrderByWithRelationInput | Prisma.ProfileTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProfileTranslations.
   */
  cursor?: Prisma.ProfileTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileTranslations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProfileTranslations.
   */
  distinct?: Prisma.ProfileTranslationScalarFieldEnum | Prisma.ProfileTranslationScalarFieldEnum[]
}

/**
 * ProfileTranslation findMany
 */
export type ProfileTranslationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationInclude<ExtArgs> | null
  /**
   * Filter, which ProfileTranslations to fetch.
   */
  where?: Prisma.ProfileTranslationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProfileTranslations to fetch.
   */
  orderBy?: Prisma.ProfileTranslationOrderByWithRelationInput | Prisma.ProfileTranslationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProfileTranslations.
   */
  cursor?: Prisma.ProfileTranslationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProfileTranslations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProfileTranslations.
   */
  skip?: number
  distinct?: Prisma.ProfileTranslationScalarFieldEnum | Prisma.ProfileTranslationScalarFieldEnum[]
}

/**
 * ProfileTranslation create
 */
export type ProfileTranslationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationInclude<ExtArgs> | null
  /**
   * The data needed to create a ProfileTranslation.
   */
  data: Prisma.XOR<Prisma.ProfileTranslationCreateInput, Prisma.ProfileTranslationUncheckedCreateInput>
}

/**
 * ProfileTranslation createMany
 */
export type ProfileTranslationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProfileTranslations.
   */
  data: Prisma.ProfileTranslationCreateManyInput | Prisma.ProfileTranslationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProfileTranslation createManyAndReturn
 */
export type ProfileTranslationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * The data used to create many ProfileTranslations.
   */
  data: Prisma.ProfileTranslationCreateManyInput | Prisma.ProfileTranslationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ProfileTranslation update
 */
export type ProfileTranslationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationInclude<ExtArgs> | null
  /**
   * The data needed to update a ProfileTranslation.
   */
  data: Prisma.XOR<Prisma.ProfileTranslationUpdateInput, Prisma.ProfileTranslationUncheckedUpdateInput>
  /**
   * Choose, which ProfileTranslation to update.
   */
  where: Prisma.ProfileTranslationWhereUniqueInput
}

/**
 * ProfileTranslation updateMany
 */
export type ProfileTranslationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProfileTranslations.
   */
  data: Prisma.XOR<Prisma.ProfileTranslationUpdateManyMutationInput, Prisma.ProfileTranslationUncheckedUpdateManyInput>
  /**
   * Filter which ProfileTranslations to update
   */
  where?: Prisma.ProfileTranslationWhereInput
  /**
   * Limit how many ProfileTranslations to update.
   */
  limit?: number
}

/**
 * ProfileTranslation updateManyAndReturn
 */
export type ProfileTranslationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * The data used to update ProfileTranslations.
   */
  data: Prisma.XOR<Prisma.ProfileTranslationUpdateManyMutationInput, Prisma.ProfileTranslationUncheckedUpdateManyInput>
  /**
   * Filter which ProfileTranslations to update
   */
  where?: Prisma.ProfileTranslationWhereInput
  /**
   * Limit how many ProfileTranslations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ProfileTranslation upsert
 */
export type ProfileTranslationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationInclude<ExtArgs> | null
  /**
   * The filter to search for the ProfileTranslation to update in case it exists.
   */
  where: Prisma.ProfileTranslationWhereUniqueInput
  /**
   * In case the ProfileTranslation found by the `where` argument doesn't exist, create a new ProfileTranslation with this data.
   */
  create: Prisma.XOR<Prisma.ProfileTranslationCreateInput, Prisma.ProfileTranslationUncheckedCreateInput>
  /**
   * In case the ProfileTranslation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProfileTranslationUpdateInput, Prisma.ProfileTranslationUncheckedUpdateInput>
}

/**
 * ProfileTranslation delete
 */
export type ProfileTranslationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationInclude<ExtArgs> | null
  /**
   * Filter which ProfileTranslation to delete.
   */
  where: Prisma.ProfileTranslationWhereUniqueInput
}

/**
 * ProfileTranslation deleteMany
 */
export type ProfileTranslationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProfileTranslations to delete
   */
  where?: Prisma.ProfileTranslationWhereInput
  /**
   * Limit how many ProfileTranslations to delete.
   */
  limit?: number
}

/**
 * ProfileTranslation without action
 */
export type ProfileTranslationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProfileTranslation
   */
  select?: Prisma.ProfileTranslationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProfileTranslation
   */
  omit?: Prisma.ProfileTranslationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProfileTranslationInclude<ExtArgs> | null
}
