
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Profile: 'Profile',
  ProfileTranslation: 'ProfileTranslation',
  Experience: 'Experience',
  ExperienceTranslation: 'ExperienceTranslation',
  Project: 'Project',
  ProjectTranslation: 'ProjectTranslation',
  Post: 'Post',
  PostTranslation: 'PostTranslation'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ProfileScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  github: 'github',
  linkedin: 'linkedin',
  instagram: 'instagram',
  updatedAt: 'updatedAt'
} as const

export type ProfileScalarFieldEnum = (typeof ProfileScalarFieldEnum)[keyof typeof ProfileScalarFieldEnum]


export const ProfileTranslationScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  language: 'language',
  bio: 'bio',
  cvUrl: 'cvUrl'
} as const

export type ProfileTranslationScalarFieldEnum = (typeof ProfileTranslationScalarFieldEnum)[keyof typeof ProfileTranslationScalarFieldEnum]


export const ExperienceScalarFieldEnum = {
  id: 'id',
  company: 'company',
  startDate: 'startDate',
  endDate: 'endDate',
  current: 'current',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ExperienceScalarFieldEnum = (typeof ExperienceScalarFieldEnum)[keyof typeof ExperienceScalarFieldEnum]


export const ExperienceTranslationScalarFieldEnum = {
  id: 'id',
  experienceId: 'experienceId',
  language: 'language',
  position: 'position',
  description: 'description'
} as const

export type ExperienceTranslationScalarFieldEnum = (typeof ExperienceTranslationScalarFieldEnum)[keyof typeof ExperienceTranslationScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  imageUrl: 'imageUrl',
  link: 'link',
  github: 'github',
  tags: 'tags',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const ProjectTranslationScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  language: 'language',
  title: 'title',
  description: 'description'
} as const

export type ProjectTranslationScalarFieldEnum = (typeof ProjectTranslationScalarFieldEnum)[keyof typeof ProjectTranslationScalarFieldEnum]


export const PostScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  published: 'published',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PostScalarFieldEnum = (typeof PostScalarFieldEnum)[keyof typeof PostScalarFieldEnum]


export const PostTranslationScalarFieldEnum = {
  id: 'id',
  postId: 'postId',
  language: 'language',
  title: 'title',
  content: 'content'
} as const

export type PostTranslationScalarFieldEnum = (typeof PostTranslationScalarFieldEnum)[keyof typeof PostTranslationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

